version: "3"
services:
  ui:
    container_name: pomodoro-ui
    build: ui/
    ports:
      - "8080:8080"
    depends_on:
      - server
      - mongo
  server:
     container_name: pomodoro-server
     restart: always
     build: server/
     ports:
       - "3001:3001"
     links:
       - mongo
  mongo:
      container_name: pomodoro-db
      image: mongo
      ports:
        - "27017:27017"
