export default {
    GET_TASKS: "GET_TASKS",
    CREATE_TASK: "CREATE_TASK",
    DELETE_TASK: "DELETE_TASK",
    UPDATE_TASK: "UPDATE_TASK",
    START_TASK: "START_TASK",
    FINISH_TASK: "FINISH_TASK",
    CANCEL_TIMER: "CANCEL_TIMER",
    TOGGLE_COMMENT_FORM: "TOGGLE_COMMENT_FORM",
    TOGGLE_COMMENTS: "TOGGLE_COMMENTS",
    INPUT_TASK_TITLE: "INPUT_TASK_TITLE",
    INPUT_TASK_ESTIMATE: "INPUT_TASK_ESTIMATE",
    INPUT_TASK_PRIORITY: "INPUT_TASK_PRIORITY"
}
