export default {
    CREATE_TASK: "CREATE_TASK",
    DELETE_TASK: "DELETE_TASK",
    UPDATE_TASK: "UPDATE_TASK",
    START_TASK: "START_TASK",
    FINISH_TASK: "FINISH_TASK",
    SORT_TASKS: "SORT_TASKS",
    ADD_COMMENT: "ADD_COMMENT",
    TOGGLE_COMMENT_FORM: "TOGGLE_COMMENT_FORM"
}
